# Generated by Django 4.2.5 on 2023-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_created_at_alter_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='memo',
            field=models.TextField(default=''),
        ),
    ]
