# Generated by Django 4.2.5 on 2023-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('capacity', models.IntegerField()),
                ('is_parking_available', models.BooleanField()),
                ('opening_time', models.TimeField(verbose_name='')),
                ('closing_time', models.TimeField(verbose_name='')),
            ],
        ),
    ]
