# Generated by Django 3.1.7 on 2023-10-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20231011_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.TextField(),
        ),
    ]
