# Generated by Django 4.2.5 on 2023-09-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='gnere',
            new_name='genre',
        ),
    ]
