# Generated by Django 4.2.5 on 2023-09-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_gnere_movies_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='UnKnown', max_length=20),
        ),
    ]
